# Generated by Django 5.0.7 on 2024-08-08 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 13, 24, 58, 500249, tzinfo=datetime.timezone.utc)),
        ),
    ]
